language: ruby
bundler_args: --without metrics
script: "bundle exec rake spec_for_build"
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - rbx-19mode
  - jruby-19mode
matrix:
  allow_failures:
    - rvm: rbx-19mode
    - rvm: jruby-19mode
